Code/app/application/exercises/routes.py
from flask import Blueprint, render_template
from flask import current_app as app


#TODO: FIX ABOVE IMPORTS

exercises_bp = Blueprint(
    'exercises_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@exercises_bp.route('/exercise/<int:id>')
def exercise(id):

    return render_template(
        'exercise.html',
        title="Exercise",
        description="Here you can see the details of a selected available exercises.",
        template='exercise-template',
        exercise=id,
        exercise_title="Sample Exercise")

@exercises_bp.route('/exercises')
def exercises():

    return render_template(
        'exercises.html',
        title="Exercises",
        description="Here you can see the list of available exercises.",
        template='exercises-template',
        exercises={
            1: 'Sample Exercise Number 1 ',
            2: 'Sample Exercise Number 2'
        })

Code/app/application/exercises/templates/exercise.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>{{title}}</h1>
        <p>{{description}}</p>
        <a href="{{ url_for('vm_bp.start_vm', vm_id=300) }}">{{ 'Start work environment' }}</a>
        <a href="{{ url_for('vm_bp.stop_vm', vm_id=300) }}">{{ 'Stop work environment' }}</a>
        <a href="{{ url_for('vm_bp.connect', vm_id=300) }}">{{ 'Connect to work environment' }}</a>
        <a href="{{ url_for('vm_bp.start_firewall', vm_id=300) }}">{{ 'Turn on exam mode' }}</a>
        <a href="{{ url_for('vm_bp.stop_firewall', vm_id=300) }}">{{ 'Turn off exam mode' }}</a>
        <a href="{{ url_for('tests_bp.ping', vm_id=300) }}">{{ 'Check exercise results' }}</a>
    </div>
{% endblock %}

Code/app/application/exercises/templates/exercises.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>{{title}}</h1>
        <p>{{description}}</p>
        {% for id, name in exercises.items() %}
            <a href="{{ url_for('exercises_bp.exercise', id=id )}}">{{ name }}</a><br>
        {% endfor %}

    </div>
{% endblock %}